### PR TITLE
Port to the latest stable Chisel release

### PR DESCRIPTION
**Pull request by ekiwi**
This PR ports the chisel hardware to use the latest stable release.
It also cleans up any deprecation warnings.

### CODE REVIEW

**Comment by tmoreau89** [comment]
Thank you @ekiwi - glad to see your changes use the latest stable release.

**Comment by tmoreau89** [comment]
@vegaluisjose @liangfu can you take a look? thanks!

**Review by vegaluisjose — APPROVED** [review]
Sweet!

**Review by tmoreau89 — APPROVED** [review]
LGTM

**Pull request merged**
