### PR TITLE
Jenkinsfile ci pipeline fix.

### PR DESCRIPTION
**Pull request by aasorokiin**
Update CI docker

### CODE REVIEW

**Comment by aasorokiin** [comment]
This request has the same issue. @vegaluisjose

**Review by vegaluisjose — APPROVED** [review]
LGTM. After merging this one, it shouldn't fail anymore because the docker image is a newer one.

**Review by tmoreau89 — APPROVED** [review]
LGTM

**Comment by aasorokiin** [comment]
Is there anything I could do to to complete this PR? @vegaluisjose

**Comment by vegaluisjose** [comment]
Hey @aasorokiin ,

It looks like the CI issue is more involved than I thought and requires some work that has to be done by someone with committer privileges. Once I have the solution, I will let you know.

**Comment by vegaluisjose** [comment]
Hey @aasorokiin ,

This was just addressed in #36 , so I am closing this one now.

**Pull request closed without merging**
